### PR TITLE
feat(tiles) Allow custom tile prioritisation 

### PR DESCRIPTION
**Pull request by Gmadges**
Hi there

Here is a PR that is trying to add custom prioritisation loading for tileset tiles.
My goal was to prioritise tiles that are closer to the center of the screen
It's a bit rough at the moment, but it would be good to get some thoughts on implementation or on whether this is a feature that would be wanted upstream.
I'm happy to shape it into something more useful

Thoughts:
- Should we allow a "PriorityFunc" to be passed to the Tileset3D so users could define custom priority metrics (As I have done here)
- Is it problematic to expect the viewport's project function to be present?

### CODE REVIEW

**Comment by ibgreen** [comment]
@Gmadges Thanks for the PR. I fully agree that loading from the center is a highly desirable feature!

One problem making it hard to accept this PR is that the traversal part is the hackiest part of the 3D tile implementation in loaders.gl, it is very complex to maintain, it has a lot of issues that need to be addressed. We are most likely heading for a complete rewrite in the not too distant future.

Therefore I worry about adding new complexity at this stage. 

I would be more comfortable with a smaller change that provided some hook / callback that the application could use to override things, than modifying logic in the existing traversal code, if that makes sense.

**Comment by Gmadges** [comment]
Hi @ibgreen, That makes sense thanks for the heads up!

If I get a chance I can try and cut this PR down to something even lighter touch.

Otherwise, I'm happy to help with any work needed towards a rewrite, we have a bit of experience with tilesets and HLOD rendering (especially pointclouds)

**Comment by ibgreen** [comment]
Would love to collaborate. If possible, ping me on the deck.gl slack and we can discuss in more detail.

https://deck.gl/docs/get-started/learning-resources#community

**Review by ibgreen — CHANGES_REQUESTED** [review]
Just marking this to reflect the conclusion of the discussion.

**Pull request closed without merging**
