### PR TITLE
gdal: Wrapper for gdal-js (WIP)

### PR DESCRIPTION
**Pull request by ibgreen**
Initial stab at a test integration of gdal-js. 

Note: the wasm library loader is not working yet.

- Unfortunately it looks like gdal-js is built with support for raster formats only? 
- And even with those limitations, the libs folder is 7MB...

| KB | file 
|--- | ---
| 844	| src/libs/gdal.data
| 152	| src/libs/gdal.js
| 6264	| src/libs/gdal.wasm

### CODE REVIEW

**Comment by kylebarron** [comment]
> * Unfortunately it looks like gdal-js is built with support for raster formats only

Yes, see https://github.com/ddohler/gdal-js/issues/33. If we were going to try to compile `gdal-js` with vector support, it might make sense to have separate gdal-raster and gdal-vector bundles.

> * And even with those limitations, the libs folder is 7MB...

I think that if we wanted to optimize better for bundle size, we'd modify the `gdal-js` compilation targets. In the [`Makefile`](https://github.com/ddohler/gdal-js/blob/develop-js/Makefile#L97) the desired exported functions are listed, so we could probably reduce the number of functions linked.

I.e. if we only care about loading formats, and maybe reprojection as well, I think there are several commands we could remove.

As an aside, I'm guessing that `gdal-js` also compiles with `proj`, the reprojection library, and I wouldn't be surprised if that took up a good chunk of the bundle size.

**Comment by ibgreen** [comment]
>  think that if we wanted to optimize better for bundle size, we'd modify the gdal-js compilation targets. In the Makefile the desired exported functions are listed, so we could probably reduce the number of functions linked.

He already mentioned that to manage size he only included two formats out of their big catalog...

> As an aside, I'm guessing that gdal-js also compiles with proj, the reprojection library, and I wouldn't be surprised if that took up a good chunk of the bundle size.

Yes good point. But how modular is that C++ code in terms of being able to omit such things so they can be handled in JS? It can require a lot of work to get it configured just right, and to keep that working through GDAL version updates.

**Comment by kylebarron** [comment]
> He already mentioned that to manage size he only included two formats out of their big catalog...

Yes but GDAL does much more than decode images. Among other things, his bundle includes:

- `GDALTranslate`: Convertion between formats, potentially performing some operations like subsettings, resampling, and rescaling pixels in the process.
- `GDALWarp`: Image reprojection
- `GDALDEMProcessing`: Code to create hillshading; slope/aspect maps
- `GDALRasterize`: Rasterizing vector geometries

So the main question would be: what do we want GDAL for? If we want it just to support loading data into memory, we can remove all of the above utilities, and just figure out how to use GDAL commands to create an ImageData instance.

> Yes good point. But how modular is that C++ code in terms of being able to omit such things so they can be handled in JS? It can require a lot of work to get it configured just right, and to keep that working through GDAL version updates.

From what I know about GDAL, I believe it's designed to be modular. In the existing `gdal-js` builds, he's able to pick and choose the utilities he needs.

But I agree that getting things configured can be tricky: in fact `gdal-js` _hasn't_ been updated for GDAL version updates. The repo says it's a port of GDAL 2.1, which at this point is over two years old, and there's since been a new major GDAL version (3.1). He also hasn't changed emscripten versions because newer ones broke the existing setup.

**Comment by ibgreen** [comment]
> So the main question would be: what do we want GDAL for?

Yes, that is basically the reason I created this PR, trying to answer that. 

But there is rapidly increasing overlap between loaders.gl and GDAL, and the GDAL project has been tackling similar problems since 1998, so there is clearly a lot of good work done there.

For instance of [shapefiles](https://gdal.org/drivers/vector/shapefile.html), they appear to have quite mature support for zipped shapefiles, can even read multiple shapefiles from a zip as layers into a dataset. 

```
Compressed files
Starting with GDAL 3.1, the driver can also support reading, creating and editing .shz files (ZIP files containing the .shp, .shx, .dbf and other side-car files of a single layer) and .shp.zip files (ZIP files contains one or several layers). Creation and editing involves the creation of temporary files.
```

**Comment by kylebarron** [comment]
> 6264	src/libs/gdal.wasm

Is that compressed or uncompressed?

From https://github.com/visgl/loaders.gl/issues/757#issuecomment-636379747 I thought it compressed down to 2.2MB, which is much more manageable than >6MB compressed.

Also I've read that _parsing_ JS can take quite a while. Since WASM is basically machine code, is it faster to run once downloaded?

**Comment by kylebarron** [comment]
Also did you consider https://github.com/azavea/loam at all? Even if we don't use it, it might give clues for how to best use `gdal-js`.

**Comment by ibgreen** [comment]
>  thought it compressed down to 2.2MB, which is much more manageable than >6MB compressed.

Well yes package authors like quoting compressed sizes, for obvious reasons. I was comparing apple to apple with other deps. As perspective, the entire kepler.gl bundle is 1.6MB compressed, and this is 2.2MB compressed for one dependency.

> https://github.com/azavea/loam

Took a look, seems very similar, also an images-only build (TIFF). The dynamic loading code is perhaps a bit better organized.

**Comment by kylebarron** [comment]
> Took a look, seems very similar, also an images-only build (TIFF). The dynamic loading code is perhaps a bit better organized

Yes, it's just a wrapper around `gdal-js`, so the GDAL WASM is the same. But above you said the WASM loader wasn't working yet? And looking at this might be a helpful resource.

Additionally the GDAL C++ API can be quite verbose, so if we go ahead with optional WASM GDAL, `loam` would be a great reference for working with GDAL.

**Comment by Joonalai** [comment]
Hi all.

I have done some experimenting with newest (master) GDAL / OGR. It uses PROJ>=6 (which uses sqlite3), so it was not as straight forward to compile. I managed to build gdal.js with gdal.wasm as well as ogr2ogr.js. 

Some of the drivers require extra included libraries and add more complexity to the build pipeline. At this time at least the following format conversions are working nicely with ogr2ogr.js:

* csv -> GeoJSON, Pg dump, GML, KML, 
* shp -> GeoJSON, Pg dump, GML, KML, 

Which formats are the most important ones for your use case?

**Comment by ibgreen** [comment]
Hi @Joonalai, 

Yes those formats sound like a good start. 

My understanding is that GDAL has an internal representation of geometry layers in terms of layers, features, geometry etc (an extended geojson model). 

Are those OGR classes available in JavaScript so we can iterate over the loaded result and convert it to loaders format? If so, as a possible idea for how phase 2, instead of just converters between formats, we could created converter from/to that format and make these loaders/writers integrate with the rest of loaders.gl.

`GDAL_GMLWriter`, `GDAL_KMLWriter` etc

**Comment by Joonalai** [comment]
Yes, GDAL or OGR in this case has a internal [vector data model](https://gdal.org/user/vector_data_model.html#vector-data-model). Those OGR classes can be exported to be available in JavaScript using gdal.js. 

It is possible to write custom converters based on that but one way would be to add [loaders.gl specific driver](https://gdal.org/tutorials/vector_driver_tut.html), which can be used in reading and writing inside (or outside) JavaScript.

**Pull request closed without merging**
