### PR TITLE
fix MVT empty binary tiles

### PR DESCRIPTION
**Pull request by padawannn**
Issue https://github.com/visgl/deck.gl/issues/5534

Some comments about the PR here: https://github.com/visgl/deck.gl/issues/5534#issuecomment-788972867

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]

**Review by kylebarron — CHANGES_REQUESTED** [review]
This will I think break if any input GeoJSON data is 3 dimensional, because it will think that there are both 2d and 3d data. Why not just pass `options.coordLength: 2` in the top-level options (or maybe provide a default there):

E.g. set
https://github.com/visgl/loaders.gl/blob/835a9e770f721eea2f15fcc766c818ad597e289f/modules/gis/src/lib/geojson-to-binary.js#L7

to 
```js
    coordLength: options.coordLength || firstPassData.coordLength || 2,
```

**Comment by ibgreen** [comment]
> This will I think break if any input GeoJSON data is 3 dimension

If this change passed tests, maybe we are missing a test case?

**Comment by kylebarron** [comment]
I looked a little closer and see that this wouldn't actually break code because I forgot we call `Math.max(...coordLengths)`, so initializing to `2` isn't a problem. That said I think it's not entirely clear why we'd be initializing with `Set([2])`, so I'd recommend instead changing the `Math.max` line to

```js
coordLength: coordLengths.size > 0 && Math.max(...coordLengths),
```

and keeping the `secondPass` call as mentioned above as
```js
    coordLength: options.coordLength || firstPassData.coordLength || 2,
```
Then it's clear that 2 is being used as the fallback when a `coordLength` can't be found in the data.

**Comment by padawannn** [comment]
@kylebarron I've done your requested changes. Tomorrow I'll add some extra tests

**Comment by padawannn** [comment]
@ibgreen, @kylebarron 
- I've included some extra checks in this test https://github.com/visgl/loaders.gl/blob/250fb0cc7342705ebc033e5715abba74fb47ea1c/modules/mvt/test/mvt-loader.spec.js#L208 to check that the size is two if the mvt is empty 
- Currently, we have tests for 3D and 2D GeoJson https://github.com/visgl/loaders.gl/blob/250fb0cc7342705ebc033e5715abba74fb47ea1c/modules/gis/test/geojson-to-binary.spec.js#L50 https://github.com/visgl/loaders.gl/blob/250fb0cc7342705ebc033e5715abba74fb47ea1c/modules/gis/test/geojson-to-binary.spec.js#L82 so no need to add new tests.

- The lint check is failing but the problem is in the master branch. The problem is in these files:
```
examples/experimental/gltf-with-raw-webgl/Glb.js
examples/experimental/gltf-with-raw-webgl/GlbBuilder.js
examples/experimental/gltf-with-raw-webgl/index.js
examples/experimental/gltf-with-raw-webgl/lib/gl-matrix.js
examples/experimental/gltf-with-raw-webgl/README.md
examples/experimental/gltf-with-raw-webgl/Utils.js
```
These files comes from this commit https://github.com/visgl/loaders.gl/commit/835a9e770f721eea2f15fcc766c818ad597e289f and the PR is https://github.com/visgl/loaders.gl/pull/1225

**Review by kylebarron — APPROVED** [review]
Looks good to me, I made a PR to fix CI https://github.com/visgl/loaders.gl/pull/1244, might be ideal to get that merged, then merge master back into this branch?

**Comment by dryabinin-actionengine** [comment]
@kylebarron @ibgreen  I am going to publish this changes in 2.3.13 release but when I am testing I see an error in browser test:
image
Look like all `positions.size ` are `infinity` values in browser.
Please fix this issue and let me know. I will publish it as soon as possible.

**Comment by kylebarron** [comment]
Doesn't CI test in a browser environment too? But that didn't fail; so is this result only on a specific browser? Do you get this failing test only on the 2.3 branch, and not on master? In that case maybe another PR needs to also come into the 2.3 branch.

**Comment by padawannn** [comment]
I just ran a test in the master branch and all the tests pass. The new code exists in the master branch but not in the 2.3-release branch:
https://github.com/visgl/loaders.gl/blob/2.3-release/modules/mvt/test/mvt-loader.spec.js#L209
https://github.com/visgl/loaders.gl/blob/master/modules/mvt/test/mvt-loader.spec.js#L208

I'm sorry but I don't know exactly how you do the publishing process

**Comment by kylebarron** [comment]
> I just ran a test in the master branch and all the tests pass

Can you try the tests on the `2.3-release` branch locally?

```
git checkout 2.3-release
git cherry-pick 129d348bbd8f16b53822cb1a93ecd263d49ab6c6
```
Then run the tests. The commit hash is the one from this PR https://github.com/visgl/loaders.gl/commit/129d348bbd8f16b53822cb1a93ecd263d49ab6c6

**Comment by padawannn** [comment]
@kylebarron following your instructions, tests on my 2.3-release local branch pass but I get theses errors

Captura de pantalla 2021-03-04 a las 21 24 44

I think it has nothing to do with it but it would be good if you would review it

I had to run `yarn bootstrap` first. @dryabinin-actionengine maybe it's your problem

**Comment by kylebarron** [comment]
> but I get theses errors

I think that just means you needed to rebuild some modules for 2.3, aka run `yarn bootstrap`.

**Comment by padawannn** [comment]
> After running `yarn bootstrap` and then running the tests again, did they all pass on browser tests for you?

Yes but I get the errors shown in the image above (I have done it again and I get the same result).

**Comment by kylebarron** [comment]
I ran 
```
git checkout 2.3-release
git pull origin 2.3-release
yarn bootstrap
git cherry-pick 129d348bbd8f16b53822cb1a93ecd263d49ab6c6
yarn test
```
and the tests ran
```
...
1..2696
# tests 2696
# pass  2693
# fail  3

browser-driver: Browser Test completed in 38.4s.
browser-driver: Browser Test failed: 3 tests failed
```

**Comment by padawannn** [comment]
@kylebarron can you run `yarn bootstrap ` after `git cherry-pick 129d348bbd8f16b53822cb1a93ecd263d49ab6c6 ` instead of before?

**Comment by padawannn** [comment]
I ran
```
git clone git@github.com:visgl/loaders.gl.git
git checkout 2.3-release
git pull origin 2.3-release
git cherry-pick 129d348bbd8f16b53822cb1a93ecd263d49ab6c6
yarn
yarn bootstrap
yarn test

browser-driver: Browser Test completed in 41.9s.
browser-driver: Browser Test successful: All tests passed
```

**Comment by kylebarron** [comment]
I don't know why but I can only reproduce when I run `yarn bootstrap` first

**Comment by padawannn** [comment]
Because I understand that tests are executed on compiled modules (after `yarn bootstrap ` has been executed) so when you ran `git cherry-pick 129d348bbd8f16b53822cb1a93ecd263d49ab6c6` you have the new tests but in the compile module you do not have the new code until executing `yarn bootstrap `

**Comment by kylebarron** [comment]
Ok but I don't see why you'd get an error about the json loader. In any case, @dryabinin-actionengine did you run `yarn bootstrap` before running those tests? I don't think either of us are able to reproduce your errors after rebuilding with `yarn bootstrap`.

**Comment by alasarr** [comment]
@dryabinin-actionengine I've created a PR to `2.3-release` with this fix and CI passing : https://github.com/visgl/loaders.gl/pull/1248

**Comment by dryabinin-actionengine** [comment]
@alasarr Yes I merged your PR to `2.3-release `branch .
@kylebarron I run `yarn bootstrap` before running those tests you are right.
@padawannn I published your changed to` 2.3.13` release and it is available on npm.

Thanks guys for fast problem investigation.

**Pull request merged**
