### PR TITLE
chore: peer dependency major version only

### PR DESCRIPTION
**Pull request by belom88**

### CODE REVIEW

**Review by ibgreen — COMMENTED** [review]
@Pessimistress thoughts? I think we normally request a more recent version.

**Comment by Pessimistress** [comment]
I don't have a strong opinion about this. Technically previous minor versions could be missing some features, so setting the peer dependency to the same minor version is probably the most correct. However we use major versions in deck.gl's peer deps mainly for convenience (sometimes we forget to update it when releasing a new minor version) and it does not seem to cause any troubles.

**Comment by ibgreen** [comment]
@belom88 Could we require the same minor version `^3.2.0` in this case?

**Comment by usefulthink** [comment]
can someone have a look at this?

This is currently making it impossible to install `@loaders.gl/core@3.2.3` without using `npm install --force` and a ton of peer-dependency warnings:

```
$ npm install @loaders.gl/core@3.2.3 @loaders.gl/tiles@3.2.3
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@1.0.0
npm ERR! Found: @loaders.gl/core@3.2.3
npm ERR! node_modules/@loaders.gl/core
npm ERR!   @loaders.gl/core@"3.2.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @loaders.gl/core@"3.2.0" from @loaders.gl/tiles@3.2.3
npm ERR! node_modules/@loaders.gl/tiles
npm ERR!   @loaders.gl/tiles@"3.2.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Review by Pessimistress — APPROVED** [review]

**Pull request merged**
