### PR TITLE
Tiles traverser: do not check for visibility in `canTraverse`. (#3032)

### PR DESCRIPTION
**Pull request by Avnerus**
Hi,
This is a version of PR #3032 for the 4.2-release branch.

### CODE REVIEW

**Comment by ibgreen** [comment]
Make sure to check in the lock file. If you install locally and the lock file doesn't change you may want to install volta, which automatically configures yarn and node versions.

**Comment by Avnerus** [comment]
Ah I see. It did change, but I thought I should not commit it to avoid unnecessary changes to the branch.
I'll add it then.

**Comment by Avnerus** [comment]
The current failure happened to me locally as well but I was hoping it was only local.
I checked it earlier and this seems to be something that was fixed in `master` in the _parquet_ module.

**Comment by ibgreen** [comment]
> The current failure happened to me locally as well but I was hoping it was only local. I checked it earlier and this seems to be something that was fixed in `master` in the _parquet_ module.

Hmm yes, it looks like the `4.2-release` branch may have experienced some "rot".

**Comment by Avnerus** [comment]
> > The current failure happened to me locally as well but I was hoping it was only local. I checked it earlier and this seems to be something that was fixed in `master` in the _parquet_ module.
> 
> Hmm yes, it looks like the `4.2-release` branch may have experienced some "rot".

Would it be easier to merge this against 4.1?

**Comment by ibgreen** [comment]
closing, assuming this is shipped on 4.3

**Pull request closed without merging**
