### PR TITLE
i3s-debug: fix debug texture

### PR DESCRIPTION
**Pull request by belom88**

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
Why can't we store it on the tile?

This seems more complicated.

At least add a comment somewhere.

**Comment by belom88** [comment]
The tiles list in the tileset is mutated continually. When replace texture in the moment we are not sure that this tile will be in the list when we replace back to original texture due to frameState changing. When that tile returns to the viewport it has wrong texture image.

**Comment by belom88** [comment]
I store originalTexture outside of TileHeader because it is not declared in the class and it can be confusing to have unexpected member there in terms of OOP.

**Comment by ibgreen** [comment]
> I store originalTexture outside of TileHeader because it is not declared in the class and it can be confusing to have unexpected member there in terms of OOP.

Yes The tiles should have a `userData` subobject that is intended for application to store things on the tiles without messing with the tile "schema", which should cover this use case?

**Comment by belom88** [comment]
> > I store originalTexture outside of TileHeader because it is not declared in the class and it can be confusing to have unexpected member there in terms of OOP.
> 
> Yes The tiles should have a `userData` subobject that is intended for application to store things on the tiles without messing with the tile "schema", which should cover this use case?

Ok. It is good approach. I'll do this in another PR

**Pull request merged**
