### PR TITLE
Changed bundle config to produce dist.min.js in ES5

### PR DESCRIPTION
**Pull request by dryabinin-actionengine**

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
Line 109, let's call it `dist.dev.js`

**Comment by dryabinin-actionengine** [comment]
> Line 109, let's call it `dist.dev.js`

Done

**Comment by dryabinin-actionengine** [comment]
@ibgreen I guess we should create the same PR to the master branch. Is't it?

**Comment by ibgreen** [comment]
Yes - normally we develop all fixes on master and cherry-pick them into release branches. I suppose you can do the reverse here.

**Pull request merged**
