### PR TITLE
feat(copc): New module for COPC format

### PR DESCRIPTION
**Pull request by ibgreen**

### CODE REVIEW

**Comment by hobu** [comment]
Curious about the reasons for copc.js forking. I'm sure @connormanning would have merged patches, and we are still actively improving it.

**Comment by ibgreen** [comment]
@hobu @connormanning
I am not sure I can set aside the time to prepare PRs but I might be able to write up some feedback.
- I seem to remember that there was a hard node.js dependency that was a complete deal breaker as it got picked up by certain bundlers on the browser.
- Also was hard to access the internal COPC pieces that I need to integrate with loaders.gl infrastructure (make a loader that loads from URL, load from Blob etc using @loaders.gl/core). Like other libraries I seem to recall that it offers those features at the top level.

**Comment by connormanning** [comment]
Thanks for the notes - I will take a look through what you've done here and see if there's anything that looks straightforward to update in `copc` based on how you've implemented things.

**Comment by ibgreen** [comment]
I am starting to collect notes in #2911, let's see if that helps. 

FWIW, I would be willing to collaborate and make some PRs if we can find a way to connect and discuss. I don't want to just make random offline PRs in a fork hoping the intent is understood and that they eventually land...

**Pull request merged**
