### PR TITLE
Default to ImageBitmap when supported

### PR DESCRIPTION
**Pull request by kylebarron**
When `image.type: 'auto'` default to `ImageBitmap` when supported.

### CODE REVIEW

**Comment by kylebarron** [comment]
It looks like this doesn't pass tests because SVG can't be decoded into an `ImageBitmap`.

**Comment by ibgreen** [comment]
> It looks like this doesn't pass tests because SVG can't be decoded into an ImageBitmap.

Ah - the SVG issue comes back to bite us again. I suppose if type is auto, we should return an image for SVG. Is it hard to make this plumbing?

**Comment by kylebarron** [comment]
It looks like `context` contains the original `url`. Is that enough to determine an SVG? You could potentially pass it down here
https://github.com/visgl/loaders.gl/blob/848a89f1f87c97b94b650dae9622889eb51f3196/modules/images/src/lib/parsers/parse-image.js#L20
and access it when auto detecting the loader type.

**Comment by xintongxia** [comment]
> It looks like `context` contains the original `url`. Is that enough to determine an SVG? You could potentially pass it down here
> https://github.com/visgl/loaders.gl/blob/848a89f1f87c97b94b650dae9622889eb51f3196/modules/images/src/lib/parsers/parse-image.js#L20
> 
> 
> and access it when auto detecting the loader type.

I am using `context.url` to detect tile type in i3s loaders. However `WorkerLoaders`' parser do not have this context.

**Comment by xintongxia** [comment]
Maybe it is time to revisit createWorker util https://github.com/visgl/loaders.gl/blob/master/modules/loader-utils/src/lib/create-worker.js#L78

**Comment by ibgreen** [comment]
Close in favor of #744

**Pull request closed without merging**
