### PR TITLE
feat(arrow): upgrade to apache-arrow v13

### PR DESCRIPTION
**Pull request by ibgreen**
@trxcllnt When I upgrade to v12 or v13, arrow crashes in this test case
https://github.com/visgl/loaders.gl/blob/master/modules/arrow/test/arrow-loader.spec.ts#L55

Some kind of big int issue in that table?

image

### CODE REVIEW

**Comment by trxcllnt** [comment]
That error is from [this line](https://github.com/apache/arrow/blob/f1d2fc92f9d898fc067d46a0d032d9b117a2d7fc/js/src/ipc/metadata/message.ts#L389).

It appears the dictionary's ID is a very large bigint that we can't convert to a number?

That said, I'm not sure why we care whether the dictionary's ID is a number vs. a bigint. We should just be using it as a key into a map.

**Comment by ibgreen** [comment]
OK thanks for investigating. Sounds like a minor bug that we can safely ignore. I will disable the test case and merge.

**Comment by trxcllnt** [comment]
I will figure out why your test is failing and, if possible, fix it in Arrow.

**Comment by ibgreen** [comment]
Thanks, it is not urgent since it seems like a rare case, but a fix would be appreciated.

**Pull request merged**
