### PR TITLE
Override ocular's babel preset to produce ESM modules without regenerator runtime

### PR DESCRIPTION
**Pull request by Avnerus**

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]

**Comment by ibgreen** [comment]
@Pessimistress 

Per @Avnerus investigations, our preset-env targets are now pulling more transforms including generators.

```
It was the targets > 0.2%
changing to last 2 versions fixes it
specifically it's because of android. lots of old androids out there :slightly_smiling_face: >0.2% selects android 4
```

Are you also seeing this in deck, regenerators being pulled in again?

**Comment by Pessimistress** [comment]
Why are we doing this?

Prior to the latest change, esm was forced to use all transforms. Our agreement was that we want esm to support "most evergreen browsers", as defined by the new targets. It was never a goal to not include generators. I'm not opposed to it either way, but this change should be made in ocular-dev-tools, not a project repo.

**Comment by Pessimistress** [comment]
Ref: https://github.com/uber-web/ocular/pull/349

**Comment by ibgreen** [comment]
OK. I was certainly fine with remove the `es6` target provided that the `esm` target did not include regenerators. Since the entire reason for the existence of the `es6` target was avoiding the pesky regenerators.

@Avnerus Lets upstream the changes then, are you OK with making the ocular PR?

FWIW - I used to specify very specific browser targets that were hand picked to cover the most versions while minimizing the number of transforms, but we replaced them with looser rules. 

I will say that `Last 2 versions` seems a little aggressive, some of these browsers update every 4-6 weeks, such loose rules could result in transforms being removed between patch releases which could be an issue. But we can probably count on the laggards among the browser vendors to make sure we don't move too fast.

**Comment by Pessimistress** [comment]
> I was certainly fine with remove the es6 target provided that the esm target did not include regenerators.

We removed `es6` in the above PR because the new `esm` has less transforms than the old `es6`, and anything less transpiled is essentially `src`.

> I used to specify very specific browser targets that were hand picked to cover the most versions while minimizing the number of transforms, but we replaced them with looser rules.

Wherever you were using `es6` (aka the hand-picked targets) you should be now using `src`. I would call for caution before changing the purpose of `esm`. It is after all the default entry point for end users.

**Comment by Avnerus** [comment]
Hi!
> @Avnerus Lets upstream the changes then, are you OK with making the ocular PR?
> 
Yeah sure, so about the targets..
> I will say that `Last 2 versions` seems a little aggressive
>
An alternative could be:
`">0.25%, maintained node versions, not dead, not ie 11, not android 4.4.3"`
The result is an even smaller list than `last 2 versions` which includes more esoteric browsers such as kaios and baidu, but may be more reliable.
Lowering to `0.2%` would require more exceptions (`not chrome 49, not safari 8`). 
What do you think? I'm maybe leaning toward `>0.25% not android 4.4.3` as `last 2 versions` does sound a bit too cutting edge.

**Comment by Pessimistress** [comment]
Any arbitrary percentage number may be broken by fluctuating market share in the future (0.2% worked as intended when we made the change in February). I suggest `>0.2% and supports async-functions`

**Comment by Avnerus** [comment]
>  I suggest `>0.2% and supports async-functions`
>
To me that sounds good too! Maybe also adding `maintained node versions, not dead` ?

**Comment by ibgreen** [comment]
This should have been solved by the ocular-dev-tools bump. If possible, please verify. If it is still not fixed, let's fix in ocular.

**Pull request closed without merging**
