### PR TITLE
I3S: rename base map: Satellite

### PR DESCRIPTION
**Pull request by morphoix**

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
Looks good. Just update the satellite map as discussed.

**Comment by ibgreen** [comment]
@morphoix Can you update the satellite url and land this?

**Comment by morphoix** [comment]
> @morphoix Can you update the satellite url and land this?

the thing is that I tried but it asked some token to use it

**Comment by ibgreen** [comment]
Ah yes. Let's drop the satellite / voyager option instead. then.

**Pull request merged**
