### PR TITLE
Enable setting maximum dimensions to parse for Shapefile

### PR DESCRIPTION
**Pull request by kylebarron**
Shapefiles sometimes are stored as extra dimensions than they need to be, or the extra dimension might be garbage. For example one Shapefile has a Z dimension where all values are `-1.7976931348623157e+308`.

This PR allows parsing only a specified number of dimensions, so when `maxDim: 2`, only X and Y coordinates will be parsed (Z/M coordinates will be skipped entirely during parsing, thus is probably faster).

What should the keyword be? Spelled out `maxDimensions`?

### CODE REVIEW

**Comment by ibgreen** [comment]
> Shapefiles sometimes are stored as extra dimensions than they need to be, or the extra dimension might be garbage. For example one Shapefile has a Z dimension where all values are -1.7976931348623157e+308.

There is some kind of clue about that number - 308 is the biggest exponent a double precision floating point can represent - the binary pattern may be close to all `1`s ?

One approach could of course be to filter ridiculous values to `0` but there must be some conventions here or some mistake we are doing.


> This PR allows parsing only a specified number of dimensions, so when maxDim: 2, only X and Y coordinates will be parsed (Z/M coordinates will be skipped entirely during parsing, thus is probably faster).

> What should the keyword be? Spelled out maxDimensions?

That is fine for now!

Though I wonder if this is how other software systems handle this. Now we force all files to 2 dimensions? Maybe we should postprocess and clip to two dimensions if we find garbage in the higher dimensions?

**Comment by kylebarron** [comment]
I read through the OGR docs again and they have the following option:

> ADJUST_GEOM_TYPE=NO/FIRST_SHAPE/ALL_SHAPES. (Starting with GDAL 2.1) Defines how layer geometry type is computed, in particular to distinguish shapefiles that have shapes with significant values in the M dimension from the ones where the M values are set to the nodata value. By default (FIRST_SHAPE), the driver will look at the first shape and if it has M values it will expose the layer as having a M dimension. By specifying ALL_SHAPES, the driver will iterate over features until a shape with a valid M value is found to decide the appropriate layer type.

So it seems like sometimes M values are `nodata`... Hence those `1e-308` values might be `nodata`.

Aha! With [such a Shapefile](https://irma.nps.gov/DataStore/DownloadFile/603569), OGR's default of `FIRST_SHAPE` does automatically take off the third dimension:

```
> ogrinfo cali_nht_100k_line.shp cali_nht_100k_line -so
Geometry: Line String
...

> ogrinfo cali_nht_100k_line.shp cali_nht_100k_line -so -oo ADJUST_GEOM_TYPE=NO
Geometry: Measured Line String
```

Though if you write out to a GeoJSON, it still only writes in 2D:

```
> ogr2ogr -f GeoJSON out.json cali_nht_100k_line.shp cali_nht_100k_line -oo ADJUST_GEOM_TYPE=NO
...
"geometry": { "type": "LineString", "coordinates": [ [ -104.654584507999971, 42.263086642000076 ],
...
```

**Comment by kylebarron** [comment]
Looking back at the original spec...

In the "Measured Shape Types in X,Y Space" section:

> Shapes of this type have an additional coordinate -- M. Note that "no data" value can be specified as a value for M.

And in the "Numeric Types" section:

> Positive infinity, negative infinity, and Not-a-Number (NaN) values are not allowed in shapefiles. Shapefiles support "no data" values but they are currently used only for measures. Any floating point number smaller than -10e38 is considered to represent a "no data" value.

**Comment by kylebarron** [comment]
If we might consider doing more accurate M `nodata` parsing in the future, should this be an experimental option? `shp._maxDimensions`?

**Comment by ibgreen** [comment]
> should this be an experimental option? shp._maxDimensions?

Sure. Or we can just default it to `false` later on.

**Comment by kylebarron** [comment]
> Sure. Or we can just default it to `false` later on.

I changed to `_maxDimensions` because now I think the better long-term solution is to have separate options for `Z` and `M`. When the dataset is saved as 3 dimensions, the third dimension is _`M`_, not _`Z`_; dimensions are either `XY`, `XYM` or `XYZM`

**Review by ibgreen — APPROVED** [review]

**Pull request merged**
