### PR TITLE
gltf: when resolving accessors in post-processing, take into account accessor.byteOffset

### PR DESCRIPTION
**Pull request by dryabinin-actionengine**
There is conflict while cherry-pick process of [PR](https://github.com/visgl/loaders.gl/pull/1175) to 2.3-release branch.
@Avnerus @ibgreen Please Take a look at thit.

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
Not sure what the conflict was but this looks good to me.

**Comment by dryabinin-actionengine** [comment]
@ibgreen @Avnerus If I cherry-pick commit I got the following conflict:
image
What` accessor.value `we should use?
1) `accessor.value = new ArrayType(buffer.arrayBuffer, byteOffset, length);`

**Comment by Avnerus** [comment]
Hi,
I think (1) might be a bit better because `slice` returns a copy while the constructor method creates a view?

**Comment by dryabinin-actionengine** [comment]
> Hi,
> I think (1) might be a bit better because `slice` returns a copy while the constructor method creates a view?

Ok, Thanks!

**Pull request closed without merging**
