### PR TITLE
Flatgeobuf Loader (WIP)

### PR DESCRIPTION
**Pull request by kylebarron**
ref #717 #716 

I just took a few minutes to whip up a very small working example of a Flatgeobuf loader. ~~The following appears to work in the Node console but not in the test~~. 

Edit: I just had to coerce the ArrayBuffer to a Uint8Array, which it [looks like it expects](https://github.com/bjornharrtell/flatgeobuf/blob/a6ed69fbfcbcd931b932fb346c5416c92ceb1b33/src/ts/geojson/featurecollection.ts#L39).

For now, this takes an ArrayBuffer representing the entire FlatGeobuf file, and parses it into GeoJSON features.

There might be some changes I end up suggesting upstream, but I don't think forking would be necessary.

### CODE REVIEW

**Comment by xintongxia** [comment]
Could you add API docs? 
Maybe also add a renderable example?

**Comment by kylebarron** [comment]
I should've been more clear and published this as a Draft, but for now this is just to have a discussion point for #716 . If discussion moves forward I'll clean up the PR

**Comment by kylebarron** [comment]
In addition to providing parsing to GeoJSON, Flatgeobuf's JS library has a `generic` option, which allows you to provide a function as argument which parses the underlying flatbuffers directly. This would be very fast, especially for parsing to binary, likely zero-copy for 2D geometries, since geometries are stored as flat arrays, equivalent to our format. (Since XY and Z buffers are stored separately, you'd need a copy to interleave into one array for 3d geometries).

Additionally, the Flatgeobuf streaming parser [returns an `AsyncGenerator` of Features](https://github.com/bjornharrtell/flatgeobuf/blob/50d2e8d26f39fc169277bf6f97d788cbdaf83896/src/ts/generic.ts#L17), so it could be easily included in our streaming loaders. However as input it [requires a `ReadableStream`](https://github.com/bjornharrtell/flatgeobuf/blob/50d2e8d26f39fc169277bf6f97d788cbdaf83896/src/ts/generic.ts#L21-L22), so we'd need a helper function to create a `ReadableStream` of bytes.

**Comment by ibgreen** [comment]
> latgeobuf's JS library has a generic option, which allows you to provide a function as argument which parses the underlying flatbuffers directly. This would be very fast, especially for parsing to binary, likely zero-copy for 2D geometries

That sounds promising!

> However as input it requires a ReadableStream, so we'd need a helper function to create a ReadableStream of bytes.

Sounds like you are looking for https://github.com/visgl/loaders.gl/pull/756. I haven't landed it because I am not satisfied that the tests are sufficient.

We could also add support for a `parseStreamAsBatches` function to loader objects. In most calls to `parseInBatches`, we start with a stream and then extract and async iterator from that, so this would work well (except in some cases where the user passed in an async iterator and the util in the PR above could handle that)

**Comment by kylebarron** [comment]
> Sounds like you are looking for #756. I haven't landed it because I am not satisfied that the tests are sufficient.

Yes that looks helpful. It sounds like we could plug that into a `FlatgeobufLoader` and streaming would just work.

> We could also add support for a `parseStreamAsBatches` function to loader objects

This sounds great, as long as it's transparent to the user.

**Comment by ibgreen** [comment]
> This sounds great, as long as it's transparent to the user.

Yes that is the idea. The `parse...` functions already check what loader functions each loader object exposes and calls the most appropriate one for the situation.

**Comment by ibgreen** [comment]
> Yes that looks helpful. It sounds like we could plug that into a FlatgeobufLoader and streaming would just work.

You are welcome to try, if that works that would give me the confidence I need to land the async iterator to stream PR. Right now that utility has never been used so feels wrong to land completely unproven code given the subtleties involved.

**Comment by ibgreen** [comment]
Closing in favor of #880 (don't want to push commits to this PR since it is on a fork).

**Pull request closed without merging**
