### PR TITLE
las: upgrade the laz-perf script to the last version

### PR DESCRIPTION
**Pull request by zarov**
Instructions on how to update the script in the future have been added to the header of the file.

This solves #865.

Note: this version is lighter than the previous one, I am not sure if I have done something wrong here. I saw a bunch of modifications on this file, but I don't understand the meaning of it (for example here https://github.com/visgl/loaders.gl/commits/0f2c7ace8cf3b46167702b912cc817eaef9146f3/modules/las/src/laz-perf.js).

I also took the liberty of beautifying it, to match a little what was present before, but the compiled version is minimized, so I don't know what's preferred here ?

### CODE REVIEW

**Comment by ibgreen** [comment]
It would be nice if you added the new test file (https://github.com/hobu/laz-perf/blob/master/test/raw-sets/extrabytes.laz) to `modules/las/test/data` and added a new test case in `modules/las/test` that shows it passing.

We should also add an entry in docs/what's new to mention that the las parser has been updated. We could say "Noe uses a newer version of the laz-perf parser". Unfortunately, there is not too much changelog info in the laz-perf repo.

**Comment by ibgreen** [comment]
Also I am trying to understand if the latest version supports the newer LAS 1.4 format. I see the laz-perf releases in the 1.4 range were released this year. Are those what included https://github.com/hobu/laz-perf/releases?

**Comment by ibgreen** [comment]
To fix the CI errors, add `// @ts-nocheck` and `/* eslint-disable */` to the top of the file.

**Comment by zarov** [comment]
> It would be nice if you added the new test file (https://github.com/hobu/laz-perf/blob/master/test/raw-sets/extrabytes.laz) to modules/las/test/data and added a new test case in modules/las/test that shows it passing.

Ok, I'm doing that.

> We should also add an entry in docs/what's new to mention that the las parser has been updated. We could say Now uses a newer version of the laz-perf parser.

Done

> Also I am trying to understand if the latest version supports the newer LAS 1.4 format.

From what I read, the LAZ format (as in LASZip) doesn't support the LAS 1.4 format, only 1.3. However I can do the LAS 1.4 update in another PR if you want, there doesn't seem to be a lot of new things beside a different header and new Point Data Record Format (see this document https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf )

**Comment by ibgreen** [comment]
OK that makes sense and is consistent with some comments hobu himself left in that issue https://github.com/visgl/loaders.gl/issues/591.

Regardless, I suppose we may just as well update to the latest laz-perf release if we are going through the trouble anyway.

But my intention is not to keep adding more work, let's get this PR through CI and landed.

**Pull request merged**
