### PR TITLE
Fix require is not defined (rollup) (#1011)

### LINKED ISSUE #1011: get-started-rollup build failed
yarn build result:

<details>

```
node_modules/@loaders.gl/core/dist/esm/lib/api/parse.js -> node_modules/@loaders.gl/core/dist/esm/lib/loader-utils/parse-with-worker.js -> node_modules/@loaders.gl/core/dist/esm/lib/api/parse.js
[!] Error: 'toArrayBuffer' is not exported by node-resolve:empty.js, imported by node_modules/@loaders.gl/core/dist/esm/javascript-utils/binary-utils.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@loaders.gl/core/dist/esm/javascript-utils/binary-utils.js (2:9)
1: import { assert } from '@loaders.gl/loader-utils';
2: import { toArrayBuffer as bufferToArrayBuffer } from '../node/utils/to-array-buffer.node';
            ^
3: export function toArrayBuffer(data) {
4:   if (bufferToArrayBuffer) {
Error: 'toArrayBuffer' is not exported by node-resolve:empty.js, imported by node_modules/@loaders.gl/core/dist/esm/javascript-utils/binary-utils.js
    at error (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at handleMissingExport (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:9725:28)
    at Module.traceVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:10163:24)
    at ModuleScope.findVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:8770:39)
    at FunctionScope.findVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at IfStatement.bind (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at BlockStatement$1.bind (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3148:31)

error Command failed with exit code 1.
```

</details>

### PR DESCRIPTION
**Pull request by but0n**
Fixes #1011

### CODE REVIEW

**Comment by ibgreen** [comment]
@kyle I don't see any github actions CI tests?

**Comment by kylebarron** [comment]
Ah, I guess I need to look into the syntax a bit closer. I suppose the existing Github Actions tests only run for a PR from the existing repo, not from an external repo.

**Comment by ibgreen** [comment]
@but0n We just updated the CI rules in GitHub actions., they should hopefully run if you update (or worst case close and reopen) this PR.

I can't merge this without having a clean CI run.

**Comment by kylebarron** [comment]
I believe once @but0n merges the latest master, the tests should run.

**Comment by ibgreen** [comment]
@but0n I suspect you will need a 2.3.x patch release with this commit?

**Comment by but0n** [comment]
> @but0n I suspect you will need a 2.3.x patch release with this commit?

@ibgreen Yes, thank you very much.

**Comment by kylebarron** [comment]
@but0n  We expect to publish a new patch release early next week.

**Pull request merged**
