### PR TITLE
Add github actions script

### PR DESCRIPTION
**Pull request by kylebarron**
Travis CI's wait times have been extremely long lately. This switches from Travis to Github Actions for CI testing.

### CODE REVIEW

**Review by Pessimistress — APPROVED** [review]
Nice. We may want to move the other repos too.

**Comment by kylebarron** [comment]
I think @ibgreen has expressed interest in moving other repos to GH Actions in the near future as well.

**Comment by ibgreen** [comment]
Yes we should move the lot. I could potentially ask @vdunaev and his team to help.

**Comment by kylebarron** [comment]
The deck.gl CI script is a little more complex and might take a little time, but other repos should be pretty straightforward.

**Comment by alasarr** [comment]
That's super cool!

**Pull request merged**
